[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fmt]
int_types = "short"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
